Help/src/applet-tips-dialog.c

cairo_dock_show_tips() calls _cairo_dock_get_next_tip(pTips) , which uses pTips->pCategoryCombo , so this must be properly created (initialized) before calling _cairo_dock_get_next_tip(pTips).

Help: initialize pCategoryCombo before used

---

src/CMakeLists.txt

build: ensure that symbols used by plugins are available

---

src/cairo-dock-user-interaction.c
src/gldit/cairo-dock-desktop-manager.c
src/gldit/cairo-dock-desktop-manager.h
src/implementations/cairo-dock-wayfire-integration.cpp

Explicitly try to lose keyboard focus when presenting a class of windows (using scale or similar plugin). This will only have effect on Wayfire (since the function is only available on Wayland, and this feature is only implemented for Wayfire in this case), where it is required, as layer-shell surfaces take precedence for keyboard focus (see [here](https://github.com/WayfireWM/wayfire/issues/2422)). Also avoid calling scale with no app-id.

Fixes for presenting a window class on Wayfire

---

CMakeLists.txt
Help/src/applet-tips-dialog.c
data/desktop-manager/gnome-session-3.36/gnome-session-x11@cairo-dock-compiz.target
data/desktop-manager/gnome-session-3.36/gnome-session-x11@cairo-dock-metacity.target
data/themes/default-theme-panel/launchers/01gnome-calculator.desktop
data/themes/default-theme-panel/launchers/CMakeLists.txt
data/themes/default-theme/launchers/01gnome-calculator.desktop
data/themes/default-theme/launchers/CMakeLists.txt
src/cairo-dock-user-menu.c
src/gldit/cairo-dock-applications-manager.c
src/gldit/cairo-dock-class-icon-manager.c
src/gldit/cairo-dock-class-manager.c
src/implementations/cairo-dock-X-manager.c
src/implementations/cairo-dock-X-utilities.c
tests/config.py

These include fixes unrelated to new features in the beta:
- avoid a potential crash in the Help applet
- improve window class handling and matching -- fixes #28 
- upstream patches from Debian
- bump version to 3.5.1

Backport some fixes

---

README.md
copyright
src/gldit/CMakeLists.txt
src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-desktop-file-db.c
src/gldit/cairo-dock-desktop-file-db.h
src/gldit/cairo-dock-windows-manager.c

This allows properly identifying more apps, including cases where the reported app-id / WMClass and the .desktop file name differ.
Also update the README with links to the now updated stable packages and Github Wiki

Refactor app-id matching

---

src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-dialog-manager.c

- workaround if the original .desktop file that created a launcher was deleted, but is available elsewhere on the system (partially fixes #41 ?)
- handle some edge cases better when a .desktop file can be found for an app, but it cannot be matched to its launcher
- refactor to avoid creating a new `CairoDockClassAppli` when not intended
- also fix a potential crash when a dialog is created without a corresponding icon

Improvements to matching apps

---

src/gldit/cairo-dock-dock-factory.c

Mouse position need to be updated in the drag handler, as it is only available there.

Better support dragging new launchers into the dock on Wayland

---

src/gldit/cairo-dock-class-manager.c

cairo_dock_reset_class_table () can be called whenever the current theme is reloaded / changed, which results in the DB backend also unloaded and then later crashing
TODO: add a separate function for stopping and unloading the DB backend when quiting

fix a crash when changing themes

---

src/gldit/cairo-dock-container.c
src/gldit/cairo-dock-container.h
src/gldit/cairo-dock-dock-factory.c
src/implementations/cairo-dock-X-manager.c

Allow dragging icons between docks on Wayland, using GTK's DnD facilities.

DnD improvements

---

src/gldit/cairo-dock-core.c
src/gldit/cairo-dock-desktop-manager.c
src/gldit/cairo-dock-menu.c
src/implementations/cairo-dock-cosmic-toplevel.c
src/implementations/cairo-dock-foreign-toplevel.c
src/implementations/cairo-dock-plasma-window-manager.c
src/implementations/cairo-dock-wayland-hotspots.c
src/implementations/cairo-dock-wayland-hotspots.h
src/implementations/cairo-dock-wayland-manager.c
src/implementations/cairo-dock-wayland-manager.h
src/implementations/cairo-dock-wayland-wm.c
src/implementations/cairo-dock-wayland-wm.h

Do not use relative positioning, avoiding the hack of hiding and re-showing the menu to adjust its position. Also include keyboard focus handling on Wayland with compositor-specific workarounds.

Update to menu positioning and focus handling

---

src/implementations/cairo-dock-X-manager.c
src/implementations/cairo-dock-X-manager.h
src/implementations/cairo-dock-kwin-integration.c
src/implementations/cairo-dock-plasma-window-manager.c
src/implementations/cairo-dock-plasma-window-manager.h

This makes the implemented functions (present windows & class, show desktop, "widget layer") work on KWin 5, both X11 and Wayland. Untested on KWin 6, but will likely work as well.

Kwin integration updates

---

CMakeLists.txt
src/cairo-dock-user-interaction.c
src/cairo-dock.c
src/gldit/cairo-dock-applet-facility.c
src/gldit/cairo-dock-application-facility.c
src/gldit/cairo-dock-desktop-manager.c
src/gldit/cairo-dock-desktop-manager.h
src/gldit/cairo-dock-file-manager.c
src/gldit/cairo-dock-file-manager.h
src/gldit/cairo-dock-gui-factory.c
src/gldit/cairo-dock-icon-facility.c
src/gldit/cairo-dock-menu.c
src/gldit/cairo-dock-module-manager.h
src/gldit/cairo-dock-style-facility.c
src/gldit/cairo-dock-utils.c
src/gldit/cairo-dock-utils.h
src/implementations/cairo-dock-X-manager.c
src/implementations/cairo-dock-compiz-integration.c
src/implementations/cairo-dock-wayfire-integration.c
src/implementations/cairo-dock-wayland-manager.c

New API to allow passing argument vectors, avoiding conversion to and from a pasted command line and potential quoting and escaping issues. Additionally, use g_spawn* consistently and support startup notifications for GUI programs.
Additional changes: 
- release the keyboard focus in gldi_desktop_present_windows () as well (needed on Wayfire for the scale plugin)
- add a helper function to create a submenu for selecting an app to open a file (used by several plugins)

rework launch_command() functions + small fixes

---

data/systemd/cairo-dock.service
src/gldit/cairo-dock-dialog-manager.c
src/gldit/cairo-dock-draw-opengl.c

- dialogs: close dialogs without a parent (avoids a crash on Wayland)
- systemd: ensure that child processes are not killed if Cairo-Dock exits
- fix not showing the recall image for hidden docks

Small fixes

---

src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-launcher-manager.c
src/implementations/cairo-dock-plasma-window-manager.c
src/implementations/cairo-dock-wayland-wm.c

This was not working (due to multiple reasons) since recent changes.

Fix setting a custom class / app-id for a launcher

---

CMakeLists.txt
copyright
data/scripts/cairo-dock-package-theme.sh
data/systemd/cairo-dock.service
src/cairo-dock-user-interaction.c
src/cairo-dock-user-menu.c
src/cairo-dock-widget-items.c
src/gldit/cairo-dock-applications-manager.c
src/gldit/cairo-dock-class-icon-manager.c
src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-class-manager.h
src/gldit/cairo-dock-core.c
src/gldit/cairo-dock-file-manager.c
src/gldit/cairo-dock-icon-facility.c
src/gldit/cairo-dock-icon-factory.h
src/gldit/cairo-dock-icon-manager.c
src/gldit/cairo-dock-launcher-manager.c
src/gldit/cairo-dock-module-manager.h
src/gldit/cairo-dock-struct.h
src/gldit/cairo-dock-themes-manager.c
src/gldit/cairo-dock-utils.c
src/gldit/cairo-dock-utils.h
src/gldit/cairo-dock-windows-manager.c
src/gldit/cairo-dock-windows-manager.h
src/implementations/CMakeLists.txt
src/implementations/cairo-dock-plasma-window-manager.c
src/implementations/cairo-dock-systemd-integration.c
src/implementations/cairo-dock-systemd-integration.h

Fixes #51  (hopefully also fixing the original problem there)
- Rework the way apps are launched, using `g_desktop_app_info_launch_uris_as_manager()` where possible, and defining a new backend that can operate on newly launched processes.
- Create a "systemd" backend that uses the "org.freedesktop.systemd1.Manager" interface to put child processes in their own slice (using "transient units")
- Extend the other existing APIs for launching commands to support this
- Some additional minor improvements
- Support for getting the DBus name of apps from KWin (needed for the Global-Menu plugin)

Support putting apps in a separate systemd slice

---

src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-menu.c
src/gldit/cairo-dock-windows-manager.c
src/gldit/cairo-dock-windows-manager.h
src/implementations/cairo-dock-X-manager.c
src/implementations/cairo-dock-X-utilities.c
src/implementations/cairo-dock-X-utilities.h

This seems necessary to identify some apps.

X11: use the res_name part of WM_CLASS as well

---

src/gldit/cairo-dock-container.c
src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-dock-factory.h

This can lead to crashes on newer GTK versions. It is simpler to just call our signal handlers directly.
This backports changes proposed for the development version that fix a critical bug.

backport: container: do not emit "fake" leave/enter events

---

CMakeLists.txt
src/cairo-dock-user-interaction.c
src/gldit/cairo-dock-container.c
src/gldit/cairo-dock-container.h
src/gldit/cairo-dock-dialog-manager.c
src/gldit/cairo-dock-dock-facility.c
src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-dock-manager.c
src/gldit/cairo-dock-module-manager.h

Following up on #76 this switches to the new API and removes the old `cairo_dock_emit_*` functions. This makes it clear that these functions are used only for docks. This is also an API / ABI break (just in time to include in 3.6.0)

Update API for synthetic leave / enter events

---

src/gldit/cairo-dock-desklet-manager.c
src/implementations/cairo-dock-wayland-wm.c

This allows better using a compositors interface for placement rules.

desklet-manager: make desklets distinguishable on Wayland

---

CMakeLists.txt
data/desktop-manager/gnome-session-3.28/CMakeLists.txt
data/desktop-manager/gnome-session-3.36/CMakeLists.txt
data/systemd/CMakeLists.txt

Previously, these would always be installed under `/usr/local` which could interfere with system packages. This ensures that everything is installed under the prefix selected by the user.
Note: this can cause our sessions not showing up on the login screen if the install prefix is not a standard system location (`/usr/local` still seems to work at least on Ubuntu). If needed, the necessary files can be symlinked to the appropriate locations.

desktop-manager: install files within our installation prefix

---

src/gldit/cairo-dock-dock-factory.c

This happened only for icons with data renderers (e.g. Nautilus) which inhibited normal rendering with OpenGL in this case.

Fix subdock icons not rendering for already-open windows in some cases

---

src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-dock-manager.c
src/gldit/cairo-dock-dock-visibility.c
src/gldit/cairo-dock-dock-visibility.h

This fixes detecting overlaps with windows (on KWin) if the dock is not on the top-left monitor.

dock-visibility: properly use absolute positions on Wayland and simplify API

---

src/gldit/cairo-dock-application-facility.c
src/gldit/cairo-dock-applications-manager.c
src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-module-instance-manager.c
src/gldit/cairo-dock-utils.c
src/gldit/cairo-dock-utils.h
src/gldit/cairo-dock-windows-manager.c
src/gldit/cairo-dock-windows-manager.h
src/implementations/cairo-dock-X-manager.c
src/implementations/cairo-dock-cosmic-toplevel.c
src/implementations/cairo-dock-foreign-toplevel.c
src/implementations/cairo-dock-plasma-window-manager.c

This fixes several issues that I noticed recently:
- crash in systemd-integration when starting an app with a custom launcher (no desktop file ID is given)
- crash if an applet with a subdock is moved out from a dock that is deleted + wrong position in other cases (parent window needs to be updated with GTK)
- window minimize positions should be relative to the dock's surface on Wayland (was still using absolute coordinates)

Some bug fixes

---

src/cairo-dock-widget-shortkeys.c
src/cairo-dock-widget.c
src/gldit/cairo-dock-core.c
src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-gui-factory.c
src/implementations/cairo-dock-wayland-manager.c

We cannot set global keyboard shortcuts, so it is better not to display them.

GUI: remove configuration of shortkeys on Wayland

---

src/gldit/cairo-dock-desklet-factory.c
src/gldit/cairo-dock-desktop-manager.c
src/gldit/cairo-dock-dock-facility.c
src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-dock-manager.c
src/implementations/cairo-dock-wayland-manager.c

Handle the case when desktop size becomes 0 due to all monitors removed + be more careful when repositioning docks.

Better handle removing monitors

---

src/gldit/cairo-dock-dock-facility.c

Setting the size of the GtkWindow can result in wrong positions on X11.
Also we can simplify code a bit for the legacy positioning case.

dock-facility: be more careful when setting the size of subdocks

---

CMakeLists.txt
src/gldit/cairo-dock-dock-facility.c
src/gldit/cairo-dock-dock-factory.h
src/gldit/cairo-dock-dock-manager.c
src/gldit/cairo-dock-dock-manager.h
src/gldit/cairo-dock-gui-factory.c
src/gldit/cairo-dock-module-manager.h

The screen selected in the config file might not exist. We take this explicitly into account and store separately the requested and realized screen that a dock is on.

Improve screen selection

---

src/gldit/cairo-dock-dialog-manager.c
src/gldit/cairo-dock-dock-factory.c

On Wayland, the compositor can dismiss popups any time, we need to be a bit more careful when handling these.

Fixes when closing dialogs and subdocks

---

src/gldit/cairo-dock-image-buffer.c
src/gldit/cairo-dock-opengl.c
src/gldit/cairo-dock-opengl.h
src/implementations/cairo-dock-egl.c
src/implementations/cairo-dock-glx.c

On Wayland, containers only have a valid EGLSurface if they are mapped (visible). Since we have been using the parent container's GL context when rendering icons, this would not work when the container (e.g. a subdock) is hidden (note: we require a valid EGLSurface to make current the context, since the same API is used for rendering to the surface). This can be fixed by separating the APIs used:
- `_container_make_current()` is only used when we really want to render to the container's EGLSurface
- a new function, `_offscreen_make_current()` will make current a default context without any surface for rendering to textures (note: this requires the EGL_KHR_surfaceless_context extension, but we already depended on it)
These changes are fully implemented for EGL, and partially on GLX, …

Fix rendering icons in hidden subdocks with EGL on Wayland

---

src/gldit/cairo-dock-dock-factory.c
src/gldit/cairo-dock-dock-factory.h
src/implementations/cairo-dock-wayland-manager.c

We should handle the possibility of a scale change in our configure handler. Also, we should avoid commiting our `wl_surface` manually as that can cause unexpected problems.

Avoid a possible crash when the display scale factor changes

---

src/gldit/cairo-dock-task.c

Fixes #126 (not sure what was wrong with `g_clear_object()` here though, it should be OK to use even when the object is NULL)

task: fix freeing the thread

---

CMakeLists.txt
src/cairo-dock-user-interaction.c
src/cairo-dock-user-menu.c
src/gldit/cairo-dock-class-icon-manager.c
src/gldit/cairo-dock-class-manager.c
src/gldit/cairo-dock-class-manager.h
src/gldit/cairo-dock-file-manager.c
src/gldit/cairo-dock-icon-facility.c
src/gldit/cairo-dock-icon-factory.h
src/gldit/cairo-dock-icon-manager.c
src/gldit/cairo-dock-launcher-manager.c
src/gldit/cairo-dock-module-manager.h
src/gldit/cairo-dock-user-icon-manager.c
src/gldit/cairo-dock-utils.c
src/gldit/cairo-dock-utils.h
src/implementations/cairo-dock-systemd-integration.c

When using systemd, instead of spawning commands ourselves, we should prefer to ask systemd to launch them for us as a transient service. This has the following benefits:
- It avoids a race condition with putting newly launched apps in their scope, where if an app spawns a child / forks quickly, it could be missed and only the parent would be moved to a new scope.
- On systems with systemd, this will allow us to avoid spawning processes, and thus potentially leaking our environment, fds, etc.
To achieve this, we stop using `g_app_info_launch*()` for non DBus activatable processes and instead again rely on parsing the command line ourselves.

Rework launching apps

---

src/gldit/cairo-dock-file-manager.c

This is a leftover from the recent changes.

file-manager: remove an unused function

---

src/implementations/cairo-dock-wayland-manager.c

This will confuse us tracking the active window but is actually not required (we still get the keyboard events we care about).
Fixes #140

wayland-manager: do not request keyboard interactivity on KWin

---

src/gldit/cairo-dock-class-manager.c

This is part of an ongoing effort to standardize the selection of preferred terminal emulators, see https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3

class-manager: prefer xdg-terminal-exec to start apps in terminal
